### ISSUE TITLE
Another library needed for install

### ISSUE THREAD

**Issue by kmcvicker** [PearsonEducation/bag-of-holding#13]
On Ubuntu 14.04 I had to add the library  libmysqlclient-dev, otherwise the mysqlclient gives and error of mysql_config not found.  You might want to add that lib as a possible pre-requisite for installation.  

`sudo apt-get install libmysqlclient-dev`

was the command I ran to fix it.

below is the original error

Collecting mysqlclient==1.3.6 (from -r requirements/production.txt (line 3))
  Using cached mysqlclient-1.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7he4ufhd/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/tmp/pip-build-7he4ufhd/mysqlclient/setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "/tmp/pip-build-7he4ufhd/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    OSError: mysql_config not found

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7he4ufhd/mysqlclient/

**Comment by aparsons** [comment]
Thank you for the issue. I have added some [documentation](https://github.com/aparsons/bag-of-holding/commit/80f4832635958cff7fc4d0d817a634a30d4001f5#diff-7d442b7eb49f5fc377f51e74b291cfc1) to INSTALL.md regarding additional dependencies to get Django storage engines to function properly.
