### ISSUE TITLE
Invalid block tag on line 21: ''1Location'', expected 'empty' or 'endfor'. Did you forget to register or load this tag?

### ISSUE THREAD

**Issue by ishangirdhar** [PearsonEducation/bag-of-holding#16]
Hello,

I have been trying out this application. Sadly, I don't have experience of building Django apps (yet). 
I have clone this repo and I am running it and adding some sample information to understand how ti works and what all can be done. I have encountered an error while adding environment details. When I click on locations menu on left side, it causes this error:

<img width="1907" alt="screen shot 2017-03-09 at 1 56 38 pm" src="https://cloud.githubusercontent.com/assets/2884252/23737885/c80cb012-04d0-11e7-92e3-aa71a94f0367.png">

Looks like a issue in substituting value in template. has anybody else faced this issue?

Any help on how this can be fixed will be highly appreciated.

-Ishan

**Comment by aparsons** [comment]
@ishangirdhar Thank you for your bug report! I have [fixed this issue](https://github.com/aparsons/bag-of-holding/commit/ee33dcfb037f706d3ea92c8016d7aaf8bbebf3bf) and the problem looks like it was introduced in a recent update to add internationalization support. If you find any other issues in the future, please let me know!
